name: AWS-Infrastructure

on:
  push:
    branches:
      - tshego/feat/deploy-server

env:
  AWS_REGION: "eu-west-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  id-token: write
  contents: read

jobs:
    ConfigureAwsAndTerraform:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: 'google-forms/terraform'
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                    aws-region: ${{ env.AWS_REGION }}
                    aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                    audience: sts.amazonaws.com

            - name: Check out terraform
              uses: hashicorp/setup-terraform@v3
 
            - name: Terraform Init
              run: terraform init

            - name: Terraform Plan
              id: plan
              run: terraform plan

            - name: Terraform Apply
              run: terraform apply -auto-approve


    BuildNodeServer:
      runs-on: ubuntu-latest
      needs: ConfigureAwsAndTerraform
      defaults:
        run:
          working-directory: 'google-forms/backend'
      steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
        - run: npm install
        - run: npm audit fix
        - run: npm run build --if-present
        - name: Generate deployment package
          run: zip -r deploy.zip * .[^.]* -x "**node_modules**"
        
        - name: Beanstalk Deploy for app
          uses: einaregilsson/beanstalk-deploy@v16
          with:
            aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
            application_name: google-forms-application-backend
            environment_name: google-forms-elastic-beanstalk-env
            version_label: ${{ github.run_number }}
            region: ${{ env.AWS_REGION }}
            deployment_package: "${{ github.workspace }}/google-forms/backend/deploy.zip"


